# Generated by Django 2.2.1 on 2019-05-13 06:09

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_lessons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_valid_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='SessionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PilatesClient',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='0', max_length=35, primary_key=True, serialize=False, unique=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('joined_on', models.DateField(default=datetime.date.today)),
                ('purchased_on', models.DateField(default=datetime.date.today)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientlist.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('participants', models.ManyToManyField(related_name='lessons', to='clientlist.PilatesClient')),
                ('session_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientlist.SessionType')),
            ],
        ),
    ]
