# Generated by Django 2.2.1 on 2019-06-03 22:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_lessons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_valid_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='0', max_length=35, primary_key=True, serialize=False, unique=True)),
                ('added_on', models.DateField(auto_now_add=True)),
                ('joined_on', models.DateField(default=datetime.date.today)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientlist.Card')),
            ],
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('short_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_at', models.DateTimeField(default=datetime.datetime(2019, 6, 3, 22, 0), unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('participants', models.ManyToManyField(related_name='lessons', to='clientlist.Client')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientlist.LessonType')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientlist.CardType'),
        ),
    ]
