# Generated by Django 2.2.2 on 2019-07-06 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 23, 0), unique=True),
        ),
    ]
