# Generated by Django 2.2.1 on 2019-06-03 23:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientlist.Card'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 23, 0), unique=True),
        ),
    ]
