# Generated by Django 2.2.2 on 2019-07-07 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0002_auto_20190706_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 0, 0), unique=True),
        ),
    ]
