# Generated by Django 2.2.1 on 2019-06-07 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0002_auto_20190603_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 18, 0), unique=True),
        ),
    ]
