# Generated by Django 2.2.1 on 2019-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0003_auto_20190607_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
