# Generated by Django 2.2.1 on 2019-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0004_auto_20190607_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='notes',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
