# Generated by Django 2.2.1 on 2019-06-08 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0005_auto_20190607_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='expires',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 23, 0), unique=True),
        ),
    ]
