# Generated by Django 2.2.1 on 2019-06-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0006_auto_20190608_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='num_lessons',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
