# Generated by Django 2.2.1 on 2019-06-13 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0008_auto_20190610_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='clientlist.Client'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 1, 0), unique=True),
        ),
    ]
