# Generated by Django 2.2.2 on 2019-06-23 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0009_auto_20190613_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 1, 0), unique=True),
        ),
    ]
