# Generated by Django 2.2.2 on 2019-07-03 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0011_auto_20190701_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 7, 0), unique=True),
        ),
    ]
