# Generated by Django 2.2.2 on 2019-07-04 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientlist', '0012_auto_20190703_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='held_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 1, 0), unique=True),
        ),
    ]
